name = "memos"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "be8ff8ac-5a92-4d9b-8a1c-e2af8937b14e"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "5f6d38f7410f44b18d68499ca14134e5"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes"
preview_bucket_name = "notes-files-preview"
